markdown: kramdown
timezone: Europe/Rome
future: false
favicon: /logo-5p2p-128.png
baseurl: /lamorechiama
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
